version: '3'
services:
  db:
    image: mysql:latest # MySQLを使用する場合
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # MySQLを使用する場合のrootユーザーのパスワード
    ports:
      - 3307:3306 # MySQLを使用する場合はポート番号3306をマッピング
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
